sudo: required
git:
  depth: false
services:
  - docker
env:
  global:
    - DOCKER_USERNAME=travis
script: skip
before_deploy:
  - echo $DOCKER_PASSWORD | docker login harbor.revelry-prod.revelry.net -u $DOCKER_USERNAME --password-stdin
  - export ROLLBAR_DEPLOY_ID=$(./bin/rollbar_release started)
after_deploy:
  - ./bin/rollbar_release succeeded
deploy:
  provider: script
  script: bin/docker_pub . library/wiki harbor.revelry-prod.revelry.net
  on:
    branch: master
